apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainservice
  template:
    metadata:
      labels:
        app: mainservice
    spec:
      containers:
        - name: mainservice
          image: nexus-hhgtest.motivitylabs.com:8448/mainservice:latest
      imagePullSecrets:
        - name: regsecret    
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-mainservice
spec:
  type: NodePort
  selector:
    app: mainservice
  ports:
    - name: mainserviceservice
      protocol: TCP
      port: 80
      targetPort: 80