apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: binarythistle/platformservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: service1-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: service1
  ports:
  - name: service1
    protocol: TCP
    port: 80
    targetPort: 80 